### ISSUE TITLE
Incorporate builder interface into editing posts

### ISSUE THREAD

**Issue by themeblvd** [themeblvd/theme-blvd-layout-builder#18]
* The main key in the UI will be to create some sort of box in the right column that replaces the Page Template selection that you'd see on a page.
* Filterable list of post types that the builder gets implemented into. Or maybe an option on issue #22.
* Will need to rig up something that forwards to the _template_builder.php_ page template, when custom layout is applied to post (similar to https://github.com/themeblvd/theme-blvd-layouts-to-posts/blob/master/tb-layouts-to-posts.php#L58 / https://github.com/themeblvd/theme-blvd-layouts-to-posts/blob/master/tb-layouts-to-posts.php#L344).

**Comment by kpfdigital** [comment]
Yea!
